### ISSUE TITLE
Generalize forwardAuth middleware

### ISSUE THREAD

**Issue by laurivosandi** [codemowers/passmower#40]
The forwardAuth middleware could be generalized to offer generic protection for OIDC native applications as well. This could be potentially implemented as a `middleware` attribute on the current OIDCGWClient. Once defined Middleware objects get added, whether it's enabled on Ingress depends on the ingress annotation anyway. It should have an array of HTTP request parameters that are excluded from  protection to pass through webhooks and such.  Parameters could include regex to match path and array of HTTP verbs.

**Comment by laurivosandi** [comment]
I think both middleware and OIDC secret provisioning could be toggleable, this can make it possible to add just bookmark links into Passmower:

```
apiVersion: codemowers.io/v1alpha1
kind: Application
metadata:
  name: google
spec:
  displayName: Google
  uri: https://google.com
```
